apiVersion: v1
kind: Pod
metadata:
  name: app3
  labels:
    app: app3

spec:
  containers:
    - name: nginx
      image: nginx:1.14.2
      volumeMounts:
        - name: app3-volume
          mountPath: /usr/share/nginx/html  # NGINX serves from here
  volumes:
    - name: app3-volume
      hostPath:
        path: /home/kali/Inception-Of-Things/p2/app3/srcs  # your host folder containing index.html
        type: Directory  # tells Kubernetes it's a directory
