apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
  ports:
    - protocol: TCP
      port: 80       # internal cluster port
      targetPort: 80 # container port
      nodePort: 30001 # port on your host/node
  type: NodePort


# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: app2
# spec:
#   replicas: 3
#   selector:
#     matchLabels:
#       app: app2
#   template:
#     metadata:
#       labels:
#         app: app2
#     spec:
#       containers:
#       - name: nginx
#         image: nginx:1.14.2


# ---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: app3
# spec:
#   containers:
#   - name: nginx
#     image: nginx:1.14.2
